version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: mobilplan_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata_mobilplan:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 500M
    networks:
      - mobilplan_network

  postgres_keycloak:
    image: postgres:16
    container_name: keycloak_postgres
    environment:
      POSTGRES_DB: ${KEYCLOAK_POSTGRES_DB}
      POSTGRES_USER: ${KEYCLOAK_POSTGRES_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
    volumes:
      - pgdata_keycloak:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${KEYCLOAK_POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - keycloak_network

  keycloak:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: keycloak
    command:
      - start-dev
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      postgres_keycloak:
        condition: service_healthy
    networks:
      - keycloak_network

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    environment: 
      RABBITMQ_ERLANG_COOKIE: ${RABBIT_ERLANG_TOKEN}
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBIT_VHOST}
    ports:
      - "5672:5672"
      - "15672:15672"

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

    networks:
      - mobilplan_network

networks:
  mobilplan_network:
    driver: bridge

  keycloak_network:
    driver: bridge

volumes:
  pgdata_mobilplan:
    external: true
    name: mobilplan_pgdata_mobilplan
      
  pgdata_keycloak:
    external: true
    name: mobilplan_pgdata_keycloak

  rabbitmq_data:

